name: Deploy to Firebase

on:
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    check:
        name: Check
        runs-on: ubuntu-latest
        permissions:
            contents: 'read'
            id-token: 'write'
        strategy:
            matrix:
                command: [ lint, typecheck ]
        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Setup bun
                uses: oven-sh/setup-bun@v1

            -   name: Install dependencies
                run: bun install

            -   name: ${{ matrix.command }}
                run: bun ${{ matrix.command }}


    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        needs: [ check ]
        permissions:
            contents: 'write'
            id-token: 'write'
        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Setup bun
                uses: oven-sh/setup-bun@v1

            -   name: Install dependencies
                run: bun install

            -   name: Authorize Google Cloud SDK
                id: auth
                uses: google-github-actions/auth@v2
                with:
                    create_credentials_file: true
                    workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_POOL_PROVIDER}}
                    service_account: ${{ secrets.SERVICE_ACCOUNT}}

            -   name: Authorize Google Cloud SDK
                run: echo "SERVICE_ACCOUNT_KEY=$(cat "${{ steps.auth.outputs.credentials_file_path }}" | tr -d '\n')" >> $GITHUB_ENV

            -   uses: FirebaseExtended/action-hosting-deploy@v0
                name: Deploy
                with:
                    repoToken: ${{ secrets.GITHUB_TOKEN }}
                    firebaseServiceAccount: "${{ env.SERVICE_ACCOUNT_KEY }}"
                    channelId: live
                    projectId: mariomh
