name: Continuous integration

'on': pull_request

jobs:
    check:
        name: Code check
        if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Setup Volta
                uses: volta-cli/action@v4

            -   name: Install dependencies
                run: yarn install --immutable

            -   name: Lint
                run: yarn lint

            -   name: Type check
                run: yarn typecheck
    deploy:
        name: Deploy preview
        needs: [ check ]
        if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Setup Volta
                uses: volta-cli/action@v4

            -   name: Install dependencies
                run: yarn install --immutable

            -   name: Build
                run: yarn build

            -   name: Deploy to Firebase
                uses: FirebaseExtended/action-hosting-deploy@v0
                with:
                    repoToken: '${{ secrets.GITHUB_TOKEN }}'
                    firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MARIOMH }}'
                    projectId: mariomh
